loginApiUrl: https://public-papers-burn.loca.lt/api/v1/usuarios/login
username: asesor@test.com
password: 567
listAppicationsUrl: https://brave-lizards-sell.loca.lt/api/v1/solicitud?findAll=true&statusIds=%s&userIdNumber=%s
updateAppicationUrl: https://brave-lizards-sell.loca.lt/api/v1/solicitud